language: node_js
cache:
  bundler: true
  directories:
    - node_modules
node_js:
  - "10"
install:
  - npm i -g mocha
  - npm i -g semantic-release-cli
  - npm install
script:
  - npm run cover
  - npm run check-coverage
  - npm run build
after_success: 
  - npm run report-coverage
  - npm run semantic-release


