language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "10"
install:
  - npm i -g mocha
  - npm i -g semantic-release-cli
  - npm install
script:
  - npm run test:single
after_success: 
  - npm run semantic-release


