sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 10
before_install:
  - npm i -g npm
script:
  - npm run test:single
after_success: 
  - npm run semantic-release





